# Generated by Django 5.2.1 on 2025-06-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タスク名')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('genre', models.CharField(choices=[('work', '仕事'), ('private', 'プライベート'), ('other', 'その他')], max_length=20, verbose_name='ジャンル')),
                ('priority', models.IntegerField(choices=[(1, '低'), (2, 'やや低'), (3, '中'), (4, 'やや高'), (5, '高')], verbose_name='重要度')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'タスク',
                'verbose_name_plural': 'タスク',
            },
        ),
    ]
